version: "3.3"

services:
  charismahair:
    image: elliotjreed/www.example.com
    container_name: charismahair
    restart: always
    networks:
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.www.frontend.rule=Host:www.example.com"
      - "traefik.nonwww.frontend.rule=Host:example.com"
      - "traefik.protocol=h2c"
      - "traefik.port=82"

networks:
  web:
    external: true
